apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  version: "1.29"

vpc:
  cidr: <your-vpc-cidr>

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: eks-nodes
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true